import db from './db';
import { v4 as uuidv4 } from 'uuid';

const collegesData = [
  { name: 'Indian Institute of Technology Bombay', location: 'Mumbai, Maharashtra', state: 'Maharashtra', city: 'Mumbai', fees_min: 80000, fees_max: 200000, rating: 4.8, rating_count: 5200, type: 'Government', established: 1958, website: 'https://www.iitb.ac.in', image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5b/IIT_Bombay_Logo.svg/200px-IIT_Bombay_Logo.svg.png', description: 'IIT Bombay is one of the premier engineering institutions of India, known globally for its research and innovation.', placement_percentage: 95.2, avg_package: 2100000, highest_package: 25000000, total_students: 10000, accreditation: 'NAAC A++', ranking: 1, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 200000 }, { name: 'B.Tech Electrical Engineering', duration: '4 years', fees: 200000 }, { name: 'M.Tech', duration: '2 years', fees: 100000 }, { name: 'MBA', duration: '2 years', fees: 150000 }]), facilities: JSON.stringify(['Library', 'Sports Complex', 'Hostels', 'Research Labs', 'Wi-Fi Campus', 'Gymnasium']) },
  { name: 'Indian Institute of Technology Delhi', location: 'New Delhi, Delhi', state: 'Delhi', city: 'New Delhi', fees_min: 85000, fees_max: 210000, rating: 4.7, rating_count: 4800, type: 'Government', established: 1961, website: 'https://www.iitd.ac.in', image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/IIT_Delhi_Logo.svg/200px-IIT_Delhi_Logo.svg.png', description: "IIT Delhi stands as one of India's foremost institutions of higher education, with a strong emphasis on research.", placement_percentage: 94.5, avg_package: 1950000, highest_package: 22000000, total_students: 8500, accreditation: 'NAAC A++', ranking: 2, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 210000 }, { name: 'B.Tech Mechanical Engineering', duration: '4 years', fees: 210000 }, { name: 'M.Tech', duration: '2 years', fees: 110000 }]), facilities: JSON.stringify(['Library', 'Sports Complex', 'Hostels', 'Research Labs', 'Medical Facility']) },
  { name: 'Indian Institute of Technology Madras', location: 'Chennai, Tamil Nadu', state: 'Tamil Nadu', city: 'Chennai', fees_min: 75000, fees_max: 190000, rating: 4.9, rating_count: 5500, type: 'Government', established: 1959, website: 'https://www.iitm.ac.in', image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/IIT_Madras_Logo.svg/200px-IIT_Madras_Logo.svg.png', description: 'IIT Madras is ranked No.1 in engineering among all institutions in India as per NIRF 2023.', placement_percentage: 96.1, avg_package: 2200000, highest_package: 28000000, total_students: 9200, accreditation: 'NAAC A++', ranking: 1, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 190000 }, { name: 'B.Tech Civil Engineering', duration: '4 years', fees: 190000 }, { name: 'M.Tech', duration: '2 years', fees: 95000 }]), facilities: JSON.stringify(['Library', 'Cricket Ground', 'Hostels', 'Research Labs', 'Marine Labs', 'Deer Park']) },
  { name: 'BITS Pilani', location: 'Pilani, Rajasthan', state: 'Rajasthan', city: 'Pilani', fees_min: 400000, fees_max: 600000, rating: 4.6, rating_count: 4100, type: 'Private', established: 1964, website: 'https://www.bits-pilani.ac.in', image_url: 'https://upload.wikimedia.org/wikipedia/en/d/d3/BITS_Pilani-Logo.svg', description: 'BITS Pilani is one of the top private engineering universities in India with a strong alumni network globally.', placement_percentage: 90.3, avg_package: 1600000, highest_package: 18000000, total_students: 12000, accreditation: 'NAAC A', ranking: 5, courses: JSON.stringify([{ name: 'B.E. Computer Science', duration: '4 years', fees: 600000 }, { name: 'B.E. Electronics', duration: '4 years', fees: 580000 }, { name: 'MBA', duration: '2 years', fees: 400000 }]), facilities: JSON.stringify(['Library', 'Sports Complex', 'Hostels', 'Food Court', 'Auditorium', 'Medical Center']) },
  { name: 'Manipal Institute of Technology', location: 'Manipal, Karnataka', state: 'Karnataka', city: 'Manipal', fees_min: 300000, fees_max: 500000, rating: 4.3, rating_count: 3200, type: 'Private', established: 1957, website: 'https://manipal.edu/mit.html', image_url: null, description: 'Manipal Institute of Technology is one of the top private engineering colleges in India known for excellent placements.', placement_percentage: 85.7, avg_package: 1200000, highest_package: 12000000, total_students: 15000, accreditation: 'NAAC A+', ranking: 10, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 500000 }, { name: 'B.Tech Mechatronics', duration: '4 years', fees: 480000 }]), facilities: JSON.stringify(['Library', 'Swimming Pool', 'Hostels', 'Food Court', 'Gym', 'Shopping Center']) },
  { name: 'VIT University', location: 'Vellore, Tamil Nadu', state: 'Tamil Nadu', city: 'Vellore', fees_min: 200000, fees_max: 400000, rating: 4.2, rating_count: 6800, type: 'Private', established: 1984, website: 'https://vit.ac.in', image_url: null, description: 'VIT University is a Deemed University offering technology and engineering education with global collaborations.', placement_percentage: 82.4, avg_package: 900000, highest_package: 9000000, total_students: 35000, accreditation: 'NAAC A++', ranking: 12, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 400000 }, { name: 'B.Tech AI & ML', duration: '4 years', fees: 400000 }, { name: 'B.Tech Bioinformatics', duration: '4 years', fees: 350000 }]), facilities: JSON.stringify(['Multiple Libraries', 'Sports Complex', 'Hostels', 'Shopping Mall', 'Hospitals', 'Restaurants']) },
  { name: 'SRM Institute of Science and Technology', location: 'Chennai, Tamil Nadu', state: 'Tamil Nadu', city: 'Chennai', fees_min: 180000, fees_max: 380000, rating: 4.0, rating_count: 5100, type: 'Private', established: 1985, website: 'https://www.srmist.edu.in', image_url: null, description: 'SRM Institute of Science and Technology is a deemed university with strong industry connections and global partnerships.', placement_percentage: 78.9, avg_package: 750000, highest_package: 7500000, total_students: 52000, accreditation: 'NAAC A++', ranking: 18, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 380000 }, { name: 'BBA', duration: '3 years', fees: 200000 }, { name: 'MBA', duration: '2 years', fees: 380000 }]), facilities: JSON.stringify(['Library', 'Sports Ground', 'Hostels', 'Medical Center', 'Shopping Complex', 'Bank']) },
  { name: 'Delhi Technological University', location: 'New Delhi, Delhi', state: 'Delhi', city: 'New Delhi', fees_min: 90000, fees_max: 160000, rating: 4.4, rating_count: 3700, type: 'Government', established: 1941, website: 'https://dtu.ac.in', image_url: null, description: 'DTU (formerly DCE) is one of the oldest and premier engineering institutions of Delhi with excellent placement records.', placement_percentage: 88.2, avg_package: 1100000, highest_package: 14000000, total_students: 13000, accreditation: 'NAAC A', ranking: 8, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 160000 }, { name: 'B.Tech Software Engineering', duration: '4 years', fees: 160000 }]), facilities: JSON.stringify(['Library', 'Sports Complex', 'Hostels', 'Cafeteria', 'Innovation Center', 'Auditorium']) },
  { name: 'Amity University', location: 'Noida, Uttar Pradesh', state: 'Uttar Pradesh', city: 'Noida', fees_min: 250000, fees_max: 450000, rating: 3.9, rating_count: 4500, type: 'Private', established: 2005, website: 'https://www.amity.edu', image_url: null, description: 'Amity University is a leading private university with modern campus, strong industry connections, and global programs.', placement_percentage: 75.6, avg_package: 680000, highest_package: 6000000, total_students: 125000, accreditation: 'NAAC A+', ranking: 25, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 450000 }, { name: 'BCA', duration: '3 years', fees: 250000 }, { name: 'MBA', duration: '2 years', fees: 400000 }]), facilities: JSON.stringify(['Library', 'Olympic Pool', 'Hostels', 'Food Court', 'Shopping Center', 'Amphitheater']) },
  { name: 'National Institute of Technology Trichy', location: 'Tiruchirappalli, Tamil Nadu', state: 'Tamil Nadu', city: 'Tiruchirappalli', fees_min: 60000, fees_max: 140000, rating: 4.5, rating_count: 2900, type: 'Government', established: 1964, website: 'https://www.nitt.edu', image_url: null, description: 'NIT Trichy is consistently ranked among the top NITs in India and is known for quality education and placements.', placement_percentage: 92.1, avg_package: 1400000, highest_package: 16000000, total_students: 6500, accreditation: 'NAAC A++', ranking: 3, courses: JSON.stringify([{ name: 'B.Tech Computer Science', duration: '4 years', fees: 140000 }, { name: 'B.Tech Production Engineering', duration: '4 years', fees: 130000 }]), facilities: JSON.stringify(['Library', 'Stadium', 'Hostels', 'Research Parks', 'Medical Center', 'Canteen']) },
  { name: 'Pune Institute of Computer Technology', location: 'Pune, Maharashtra', state: 'Maharashtra', city: 'Pune', fees_min: 120000, fees_max: 200000, rating: 4.2, rating_count: 1800, type: 'Private', established: 1983, website: 'https://www.pict.edu', image_url: null, description: 'PICT is one of the top engineering colleges in Pune known for its exceptional placement record in the IT industry.', placement_percentage: 91.5, avg_package: 1300000, highest_package: 10000000, total_students: 3200, accreditation: 'NAAC A', ranking: 15, courses: JSON.stringify([{ name: 'B.E. Computer Engineering', duration: '4 years', fees: 200000 }, { name: 'B.E. Information Technology', duration: '4 years', fees: 190000 }]), facilities: JSON.stringify(['Library', 'Sports Ground', 'NSS Wing', 'Placement Cell', 'Canteen', 'Workshop']) },
  { name: 'Jadavpur University', location: 'Kolkata, West Bengal', state: 'West Bengal', city: 'Kolkata', fees_min: 10000, fees_max: 50000, rating: 4.6, rating_count: 3100, type: 'Government', established: 1955, website: 'https://jadavpuruniversity.in', image_url: null, description: 'Jadavpur University is a premier technical university in Eastern India, known for outstanding academic and research output.', placement_percentage: 89.3, avg_package: 1050000, highest_package: 11000000, total_students: 18000, accreditation: 'NAAC A++', ranking: 6, courses: JSON.stringify([{ name: 'B.E. Computer Science', duration: '4 years', fees: 50000 }, { name: 'B.E. Electronics & Communication', duration: '4 years', fees: 50000 }]), facilities: JSON.stringify(['Library', 'Sports Complex', 'Hostels', 'Research Centers', 'Auditorium', 'Canteen']) },
];

export async function seedDatabase() {
  const existing = db.prepare('SELECT COUNT(*) as count FROM colleges').get() as { count: number };
  if (existing.count > 0) {
    console.log('📦 Database already seeded, skipping...');
    return;
  }

  const insert = db.prepare(`
    INSERT INTO colleges (id, name, location, state, city, fees_min, fees_max, rating, rating_count,
      type, established, website, image_url, description, placement_percentage, avg_package,
      highest_package, total_students, accreditation, ranking, courses, facilities)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  db.exec('BEGIN TRANSACTION');
  try {
    for (const c of collegesData) {
      insert.run(
        uuidv4(), c.name, c.location, c.state, c.city, c.fees_min, c.fees_max,
        c.rating, c.rating_count, c.type, c.established, c.website, c.image_url,
        c.description, c.placement_percentage, c.avg_package, c.highest_package,
        c.total_students, c.accreditation, c.ranking, c.courses, c.facilities
      );
    }
    db.exec('COMMIT');
  } catch (err) {
    db.exec('ROLLBACK');
    throw err;
  }

  console.log(`✅ Seeded ${collegesData.length} colleges successfully`);
}
