import { pool, IS_PG } from './db';

const collegesData = [
  {
    name: 'Indian Institute of Technology Madras',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    city: 'Chennai',
    fees_min: 80000,
    fees_max: 190000,
    rating: 4.9,
    rating_count: 1205,
    type: 'Government',
    established: 1959,
    website: 'https://www.iitm.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/6/69/IIT_Madras_Logo.svg',
    description: 'IIT Madras is a public technical university and one of the most prestigious institutes in India. Ranked #1 by NIRF.',
    placement_percentage: 96.1,
    avg_package: 21.4,
    highest_package: 198.0,
    total_students: 10000,
    accreditation: 'NAAC A++',
    ranking: 1,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Mechanical', 'Aerospace']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs', 'Wi-Fi Campus']),
    cutoffs: JSON.stringify({
      'JEE Advanced': { 'General': 148, 'OBC-NCL': 1000, 'SC': 3000, 'ST': 4000, 'EWS': 500 }
    })
  },
  {
    name: 'Indian Institute of Technology Delhi',
    location: 'New Delhi, Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    fees_min: 85000,
    fees_max: 200000,
    rating: 4.8,
    rating_count: 1540,
    type: 'Government',
    established: 1961,
    website: 'https://home.iitd.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Indian_Institute_of_Technology_Delhi_Logo.svg',
    description: 'IIT Delhi is a globally recognized institution for engineering and research. Ranked #2 by NIRF.',
    placement_percentage: 95.8,
    avg_package: 20.5,
    highest_package: 200.0,
    total_students: 9500,
    accreditation: 'NAAC A++',
    ranking: 2,
    courses: JSON.stringify(['Computer Science', 'Mathematics & Computing', 'Electrical', 'Civil']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Gym', 'Hospital', 'Auditorium']),
    cutoffs: JSON.stringify({
      'JEE Advanced': { 'General': 118, 'OBC-NCL': 900, 'SC': 2500, 'ST': 3500, 'EWS': 400 }
    })
  },
  {
    name: 'Indian Institute of Technology Bombay',
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    fees_min: 80000,
    fees_max: 200000,
    rating: 4.8,
    rating_count: 1650,
    type: 'Government',
    established: 1958,
    website: 'https://www.iitb.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Indian_Institute_of_Technology_Bombay_Logo.svg',
    description: 'IIT Bombay is renowned for its academic excellence, vibrant campus life, and strong alumni network.',
    placement_percentage: 95.2,
    avg_package: 21.8,
    highest_package: 367.0,
    total_students: 11000,
    accreditation: 'NAAC A++',
    ranking: 3,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Mechanical', 'Chemical']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs', 'Cafeteria']),
    cutoffs: JSON.stringify({
      'JEE Advanced': { 'General': 67, 'OBC-NCL': 500, 'SC': 1500, 'ST': 2000, 'EWS': 300 }
    })
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    location: 'Kanpur, Uttar Pradesh',
    state: 'Uttar Pradesh',
    city: 'Kanpur',
    fees_min: 80000,
    fees_max: 195000,
    rating: 4.7,
    rating_count: 1120,
    type: 'Government',
    established: 1959,
    website: 'https://www.iitk.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/a/a3/IIT_Kanpur_Logo.svg',
    description: 'IIT Kanpur is a premier institute known for its strong focus on research and development.',
    placement_percentage: 94.5,
    avg_package: 19.5,
    highest_package: 190.0,
    total_students: 8500,
    accreditation: 'NAAC A++',
    ranking: 4,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Aerospace', 'Materials Science']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Airstrip', 'Sports Complex', 'Labs']),
    cutoffs: JSON.stringify({
      'JEE Advanced': { 'General': 238, 'OBC-NCL': 1200, 'SC': 3500, 'ST': 4500, 'EWS': 600 }
    })
  },
  {
    name: 'Indian Institute of Technology Kharagpur',
    location: 'Kharagpur, West Bengal',
    state: 'West Bengal',
    city: 'Kharagpur',
    fees_min: 80000,
    fees_max: 190000,
    rating: 4.7,
    rating_count: 1380,
    type: 'Government',
    established: 1951,
    website: 'https://www.iitkgp.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1c/IIT_Kharagpur_Logo.svg',
    description: 'IIT Kharagpur is the first IIT and has the largest campus area among all IITs.',
    placement_percentage: 93.8,
    avg_package: 18.5,
    highest_package: 240.0,
    total_students: 12500,
    accreditation: 'NAAC A++',
    ranking: 5,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Mechanical', 'Architecture']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Hospital', 'Sports Complex', 'Museum']),
    cutoffs: JSON.stringify({
      'JEE Advanced': { 'General': 279, 'OBC-NCL': 1500, 'SC': 4000, 'ST': 5000, 'EWS': 800 }
    })
  },
  {
    name: 'National Institute of Technology Tiruchirappalli',
    location: 'Tiruchirappalli, Tamil Nadu',
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    fees_min: 75000,
    fees_max: 180000,
    rating: 4.6,
    rating_count: 950,
    type: 'Government',
    established: 1964,
    website: 'https://www.nitt.edu',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1b/NIT_Trichy_logo.svg',
    description: 'NIT Trichy is consistently ranked as the top NIT in India, offering excellent academic and placement records.',
    placement_percentage: 92.5,
    avg_package: 12.5,
    highest_package: 40.0,
    total_students: 6500,
    accreditation: 'NAAC A++',
    ranking: 8,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Mechanical', 'Production']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs', 'Hospital']),
    cutoffs: JSON.stringify({
      'JEE Main': { 'General': 1500, 'OBC-NCL': 5000, 'SC': 15000, 'ST': 25000, 'EWS': 3000 }
    })
  },
  {
    name: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    state: 'Rajasthan',
    city: 'Pilani',
    fees_min: 250000,
    fees_max: 550000,
    rating: 4.7,
    rating_count: 1420,
    type: 'Private',
    established: 1964,
    website: 'https://www.bits-pilani.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/d/d3/BITS_Pilani-Logo.svg',
    description: 'Birla Institute of Technology and Science, Pilani is a highly reputed private engineering institute in India.',
    placement_percentage: 94.0,
    avg_package: 18.0,
    highest_package: 133.0,
    total_students: 8000,
    accreditation: 'NAAC A',
    ranking: 15,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Mechanical', 'Chemical']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs', 'Auditorium']),
    cutoffs: JSON.stringify({
      'JEE Main': { 'General': 10000, 'OBC-NCL': 15000, 'SC': 50000, 'ST': 80000, 'EWS': 12000 } // Proxy for BITSAT
    })
  },
  {
    name: 'National Institute of Technology Karnataka',
    location: 'Surathkal, Karnataka',
    state: 'Karnataka',
    city: 'Surathkal',
    fees_min: 75000,
    fees_max: 180000,
    rating: 4.5,
    rating_count: 880,
    type: 'Government',
    established: 1960,
    website: 'https://www.nitk.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/c/cc/NITK_Surathkal_Logo.svg',
    description: 'NITK Surathkal is known for its beautiful campus and strong placements.',
    placement_percentage: 91.0,
    avg_package: 11.5,
    highest_package: 45.0,
    total_students: 6000,
    accreditation: 'NAAC A',
    ranking: 10,
    courses: JSON.stringify(['Computer Science', 'Information Technology', 'Electronics', 'Civil']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Private Beach', 'Sports Complex', 'Labs']),
    cutoffs: JSON.stringify({
      'JEE Main': { 'General': 3000, 'OBC-NCL': 8000, 'SC': 20000, 'ST': 30000, 'EWS': 5000 }
    })
  },
  {
    name: 'Vellore Institute of Technology',
    location: 'Vellore, Tamil Nadu',
    state: 'Tamil Nadu',
    city: 'Vellore',
    fees_min: 198000,
    fees_max: 350000,
    rating: 4.3,
    rating_count: 2100,
    type: 'Private',
    established: 1984,
    website: 'https://vit.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Vellore_Institute_of_Technology_seal_2017.svg',
    description: 'VIT is a prominent private university offering a wide range of undergraduate and postgraduate programs.',
    placement_percentage: 90.0,
    avg_package: 8.5,
    highest_package: 102.0,
    total_students: 35000,
    accreditation: 'NAAC A++',
    ranking: 18,
    courses: JSON.stringify(['Computer Science', 'Electronics', 'Mechanical', 'Biotechnology']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs', 'Food Court']),
    cutoffs: JSON.stringify({
      'JEE Main': { 'General': 40000, 'OBC-NCL': 60000, 'SC': 150000, 'ST': 200000, 'EWS': 50000 }
    })
  },
  {
    name: 'Jadavpur University',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    city: 'Kolkata',
    fees_min: 10000,
    fees_max: 25000,
    rating: 4.5,
    rating_count: 850,
    type: 'Government',
    established: 1955,
    website: 'http://www.jaduniv.edu.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Jadavpur_University_Logo.svg',
    description: 'Jadavpur University is known for its excellent ROI, strong research focus, and vibrant campus life.',
    placement_percentage: 92.0,
    avg_package: 10.0,
    highest_package: 85.0,
    total_students: 12000,
    accreditation: 'NAAC A',
    ranking: 11,
    courses: JSON.stringify(['Computer Science', 'Electronics', 'Mechanical', 'Arts', 'Science']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs', 'Open Air Theatre']),
    cutoffs: JSON.stringify({
      'JEE Main': { 'General': 8000, 'OBC-NCL': 20000, 'SC': 60000, 'ST': 100000, 'EWS': 12000 }
    })
  },
  {
    name: 'All India Institute of Medical Sciences New Delhi',
    location: 'New Delhi, Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    fees_min: 1600,
    fees_max: 6000,
    rating: 4.9,
    rating_count: 2500,
    type: 'Government',
    established: 1956,
    website: 'https://www.aiims.edu',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/e/ea/All_India_Institute_of_Medical_Sciences%2C_New_Delhi_Logo.svg',
    description: 'AIIMS Delhi is the premier medical college and hospital in India, ranked #1 for medical studies.',
    placement_percentage: 100,
    avg_package: 15.0,
    highest_package: 40.0,
    total_students: 3000,
    accreditation: 'NMC',
    ranking: 1,
    courses: JSON.stringify(['MBBS', 'MD', 'MS', 'B.Sc Nursing']),
    facilities: JSON.stringify(['Hospital', 'Library', 'Hostel', 'Research Labs']),
    cutoffs: JSON.stringify({
      'NEET': { 'General': 57, 'OBC-NCL': 250, 'SC': 980, 'ST': 1600, 'EWS': 200 }
    })
  },
  {
    name: 'Christian Medical College Vellore',
    location: 'Vellore, Tamil Nadu',
    state: 'Tamil Nadu',
    city: 'Vellore',
    fees_min: 40000,
    fees_max: 120000,
    rating: 4.8,
    rating_count: 1200,
    type: 'Private',
    established: 1900,
    website: 'https://www.cmch-vellore.edu',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Christian_Medical_College_Vellore_logo.svg',
    description: 'CMC Vellore is a highly respected private medical college and hospital known for compassionate care.',
    placement_percentage: 100,
    avg_package: 12.0,
    highest_package: 30.0,
    total_students: 2500,
    accreditation: 'NMC',
    ranking: 3,
    courses: JSON.stringify(['MBBS', 'B.Sc Nursing', 'MD', 'MS']),
    facilities: JSON.stringify(['Hospital', 'Library', 'Hostel', 'Labs']),
    cutoffs: JSON.stringify({
      'NEET': { 'General': 1500, 'OBC-NCL': 4000, 'SC': 12000, 'ST': 20000, 'EWS': 2000 }
    })
  },
  {
    name: 'Indian Institute of Management Ahmedabad',
    location: 'Ahmedabad, Gujarat',
    state: 'Gujarat',
    city: 'Ahmedabad',
    fees_min: 2500000,
    fees_max: 3000000,
    rating: 4.9,
    rating_count: 800,
    type: 'Government',
    established: 1961,
    website: 'https://www.iima.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Indian_Institute_of_Management_Ahmedabad_Logo.svg',
    description: 'IIM Ahmedabad is the top management institute in India, renowned globally for its MBA program.',
    placement_percentage: 100,
    avg_package: 34.0,
    highest_package: 115.0,
    total_students: 1200,
    accreditation: 'EQUIS',
    ranking: 1,
    courses: JSON.stringify(['PGP', 'PGP-FABM', 'Ph.D']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Auditorium']),
    cutoffs: JSON.stringify({
      'CAT': { 'General': 99, 'OBC-NCL': 95, 'SC': 85, 'ST': 80, 'EWS': 96 } // Percentiles approximated as ranks in UI
    })
  },
  {
    name: 'Indian Institute of Management Bangalore',
    location: 'Bangalore, Karnataka',
    state: 'Karnataka',
    city: 'Bangalore',
    fees_min: 2400000,
    fees_max: 2800000,
    rating: 4.9,
    rating_count: 750,
    type: 'Government',
    established: 1973,
    website: 'https://www.iimb.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Indian_Institute_of_Management_Bangalore_Logo.svg',
    description: 'IIM Bangalore is a leading management school, known for its rigorous academic curriculum.',
    placement_percentage: 100,
    avg_package: 33.8,
    highest_package: 110.0,
    total_students: 1100,
    accreditation: 'EQUIS',
    ranking: 2,
    courses: JSON.stringify(['PGP', 'EPGP', 'Ph.D']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Auditorium']),
    cutoffs: JSON.stringify({
      'CAT': { 'General': 150, 'OBC-NCL': 500, 'SC': 1500, 'ST': 3000, 'EWS': 250 }
    })
  },
  {
    name: 'Indian Institute of Science',
    location: 'Bangalore, Karnataka',
    state: 'Karnataka',
    city: 'Bangalore',
    fees_min: 30000,
    fees_max: 50000,
    rating: 5.0,
    rating_count: 1050,
    type: 'Government',
    established: 1909,
    website: 'https://iisc.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/d/da/Indian_Institute_of_Science_2019_logo.svg',
    description: 'IISc is India\'s premier institute for advanced scientific and technological research and education.',
    placement_percentage: 95.0,
    avg_package: 28.0,
    highest_package: 85.0,
    total_students: 4000,
    accreditation: 'NAAC A++',
    ranking: 1,
    courses: JSON.stringify(['B.Sc(Research)', 'M.Tech', 'Ph.D']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Labs', 'Research Centers']),
    cutoffs: JSON.stringify({
      'GATE': { 'General': 50, 'OBC-NCL': 150, 'SC': 400, 'ST': 600, 'EWS': 80 },
      'JEE Advanced': { 'General': 250, 'OBC-NCL': 800, 'SC': 2000, 'ST': 3000, 'EWS': 400 }
    })
  },
  {
    name: 'JNTUH College of Engineering',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    city: 'Hyderabad',
    fees_min: 35000,
    fees_max: 50000,
    rating: 4.2,
    rating_count: 650,
    type: 'Government',
    established: 1965,
    website: 'https://jntuhceh.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b3/JNTU_Hyderabad_logo.png',
    description: 'Jawaharlal Nehru Technological University Hyderabad is a premier state university.',
    placement_percentage: 85.0,
    avg_package: 6.5,
    highest_package: 41.0,
    total_students: 4000,
    accreditation: 'NAAC A',
    ranking: 65,
    courses: JSON.stringify(['Computer Science', 'Electronics', 'Mechanical', 'Civil']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Labs']),
    cutoffs: JSON.stringify({
      'EAMCET': { 'General': 1500, 'OBC-NCL': 5000, 'SC': 15000, 'ST': 20000, 'EWS': 2500 }
    })
  },
  {
    name: 'Osmania University College of Engineering',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    city: 'Hyderabad',
    fees_min: 30000,
    fees_max: 50000,
    rating: 4.3,
    rating_count: 580,
    type: 'Government',
    established: 1929,
    website: 'http://ouce.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/d/db/Osmania_University_Logo.svg',
    description: 'OUCE is one of the oldest and most reputed engineering colleges in Telangana.',
    placement_percentage: 88.0,
    avg_package: 7.0,
    highest_package: 35.0,
    total_students: 3500,
    accreditation: 'NAAC A+',
    ranking: 80,
    courses: JSON.stringify(['Computer Science', 'Electronics', 'Mechanical', 'Biomedical']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports', 'Labs']),
    cutoffs: JSON.stringify({
      'EAMCET': { 'General': 2500, 'OBC-NCL': 8000, 'SC': 25000, 'ST': 35000, 'EWS': 4000 }
    })
  },
  {
    name: 'Andhra University College of Engineering',
    location: 'Visakhapatnam, Andhra Pradesh',
    state: 'Andhra Pradesh',
    city: 'Visakhapatnam',
    fees_min: 30000,
    fees_max: 60000,
    rating: 4.2,
    rating_count: 450,
    type: 'Government',
    established: 1955,
    website: 'https://www.andhrauniversity.edu.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Andhra_University_Emblem.svg',
    description: 'A constituent college of Andhra University, known for its picturesque campus and strong academics.',
    placement_percentage: 82.0,
    avg_package: 6.0,
    highest_package: 28.0,
    total_students: 4500,
    accreditation: 'NAAC A',
    ranking: 75,
    courses: JSON.stringify(['Computer Science', 'Electrical', 'Mechanical', 'Naval Architecture']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports', 'Labs']),
    cutoffs: JSON.stringify({
      'EAMCET': { 'General': 4000, 'OBC-NCL': 12000, 'SC': 30000, 'ST': 40000, 'EWS': 6000 }
    })
  },
  {
    name: 'Chaitanya Bharathi Institute of Technology',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    city: 'Hyderabad',
    fees_min: 140000,
    fees_max: 180000,
    rating: 4.1,
    rating_count: 720,
    type: 'Private',
    established: 1979,
    website: 'https://www.cbit.ac.in',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/f/f7/CBIT_Hyderabad_Logo.svg',
    description: 'CBIT is one of the premier private engineering colleges in Telangana.',
    placement_percentage: 90.0,
    avg_package: 7.5,
    highest_package: 54.0,
    total_students: 5000,
    accreditation: 'NAAC A',
    ranking: 150,
    courses: JSON.stringify(['Computer Science', 'Information Technology', 'Electronics']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports', 'Labs']),
    cutoffs: JSON.stringify({
      'EAMCET': { 'General': 5000, 'OBC-NCL': 15000, 'SC': 45000, 'ST': 60000, 'EWS': 8000 }
    })
  },
  {
    name: 'Manipal Institute of Technology',
    location: 'Manipal, Karnataka',
    state: 'Karnataka',
    city: 'Manipal',
    fees_min: 300000,
    fees_max: 450000,
    rating: 4.4,
    rating_count: 1300,
    type: 'Private',
    established: 1957,
    website: 'https://manipal.edu/mit.html',
    image_url: 'https://upload.wikimedia.org/wikipedia/en/c/cd/Manipal_University_logo.svg',
    description: 'MIT Manipal is renowned for its excellent campus infrastructure, diverse student life, and global alumni network.',
    placement_percentage: 92.5,
    avg_package: 10.5,
    highest_package: 54.7,
    total_students: 9000,
    accreditation: 'NAAC A++',
    ranking: 55,
    courses: JSON.stringify(['Computer Science', 'Information Technology', 'Electronics', 'Mechatronics']),
    facilities: JSON.stringify(['Library', 'Hostel', 'Sports Complex', 'Innovation Center']),
    cutoffs: JSON.stringify({
      'JEE Main': { 'General': 45000, 'OBC-NCL': 65000, 'SC': 180000, 'ST': 250000, 'EWS': 55000 }
    })
  }
];

export async function seedDatabase() {
  const existing = await pool.query('SELECT COUNT(*) AS count FROM colleges');
  if (parseInt(existing.rows[0].count as string) > 0) {
    console.log('📦 Database already seeded with', existing.rows[0].count, 'colleges — skipping.');
    return;
  }

  for (const c of collegesData) {
    await pool.query(
      `INSERT INTO colleges
        (name, location, state, city, fees_min, fees_max, rating, rating_count,
         type, established, website, image_url, description, placement_percentage,
         avg_package, highest_package, total_students, accreditation, ranking, courses, facilities, cutoffs)
       VALUES
        ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)`,
      [
        c.name,
        c.location,
        c.state,
        c.city,
        c.fees_min,
        c.fees_max,
        c.rating,
        c.rating_count,
        c.type,
        c.established,
        c.website,
        c.image_url,
        c.description,
        c.placement_percentage,
        c.avg_package,
        c.highest_package,
        c.total_students,
        c.accreditation,
        c.ranking,
        c.courses,
        c.facilities,
        IS_PG ? c.cutoffs : (typeof c.cutoffs === 'string' ? c.cutoffs : JSON.stringify(c.cutoffs)),
      ]
    );
  }
  console.log('✅ Seeded 20 colleges into the database');
}
